# Generated by Django 6.0.5 on 2026-05-24 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1: Direct'), ('SCOPE_2', 'Scope 2: Indirect (Electricity)'), ('SCOPE_3', 'Scope 3: Indirect (Value Chain)')], max_length=10)),
                ('ghg_category', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(max_length=20)),
                ('normalized_quantity_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('RAW', 'Raw Ingested'), ('FLAGGED', 'Flagged for Review'), ('APPROVED', 'Analyst Approved'), ('AUDIT_LOCKED', 'Locked for Audit')], default='RAW', max_length=15)),
                ('anomaly_reason', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_sap_code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('region_grid_factor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('changes_json', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='esg_app.emissionactivityrecord')),
            ],
        ),
        migrations.AddField(
            model_name='emissionactivityrecord',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='esg_app.facility'),
        ),
        migrations.CreateModel(
            name='RawIngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Procurement'), ('UTILITY', 'Utility Portal Export'), ('CONCUR', 'SAP Concur API')], max_length=20)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg_app.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='emissionactivityrecord',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='esg_app.rawingestionjob'),
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg_app.tenant'),
        ),
        migrations.AddField(
            model_name='emissionactivityrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg_app.tenant'),
        ),
    ]
